{% set name = "tensorboard" %}
{% set version = "2.20.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/tensorflow/tensorboard/archive/refs/tags/2.20.0.tar.gz
  sha256: 7a3b3bb111a9734fd051bd34e763ae90b0a76a2549e74ec75ebcba752ba5a21a

build:
  number: 0
  skip: True  # [py<39]
  entry_points:
    - tensorboard = tensorboard.main:run_main

requirements:
  build:
    - msys2-sed # [win]
    - sed # [unix]
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - bazel 6.5.0
    - bazel-toolchain  # [osx]
    - git  # Needed by Bazel for yarn/npm operations
    - nodejs >=18  # Needed for building frontend
    - yarn  # Needed by Bazel for JS dependencies
  host:
    - python
    - pip
    - setuptools
    - wheel
    - protobuf {{ libprotobuf }}
    - absl-py
    - grpcio {{ libgrpc }}
    - numpy {{ numpy }}
  run:
    - python
    - absl-py >=0.4
    - grpcio >=1.48.2
    - markdown >=2.6.8
    - numpy >=1.12.0
    - packaging
    - pillow
    - protobuf >=3.19.6,!=4.24.0
    - setuptools >=41.0.0
    - six >1.9
    - tensorboard-data-server >=0.7.0,<0.8.0
    - werkzeug >=1.0.1    

test:
  requires:
    - pip
  imports:
    - tensorboard
  commands:
    - tensorboard -h
    - pip check

about:
  home: https://www.tensorflow.org/tensorboard
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: TensorFlow's Visualization Toolkit
  description: |
    TensorBoard is a suite of web applications for inspecting and understanding your TensorFlow runs and graphs.
  dev_url: https://github.com/tensorflow/tensorboard
  doc_url: https://www.tensorflow.org/tensorboard/get_started

extra:
  recipe-maintainers:
    - sdvillal
    - gilbertfrancois
    - farhantejani
    - mdraw
    - jschueller
    - xhochy
    - ngam
