travis:
  secure:
    BINSTAR_TOKEN: ijAfFk+gNh1+PO+JLF7B1X65wJeCJsuTnT3Fa7shiqBEyKZxd0mMBcobX/jKOZwxFdTWElvHa2P0UdOS5tp5RI5jwR3iAdryTHQRTrcBJQKJm8+W5bsorJUSwdVjQVvzft5J02t0yDb4RCxq4DnNa6FEdnbn5KCctI9z4DIT/hl67G0AmulFNPB4DXiqz27ZB9/WAhbL9GjAG/FHGC6xGtf4DOtRTQ0iIeeMan6qsxN4kVKYdJOGC6NRpG9lWtHVdxyWlycvsjMpdCDBjjDJzzQx4v1DcMDOlsWPBwPCVb41qr8/uQuNzyvmIXTMJfdgiLAi2TZbQaHTEQbn4hNUeTRb7cntg/4R6/Y5LHOi0wK7J845AQfYXnEQ+EMrJb62t5taOJfP/QuC9ZS/Rm4xhZvPGTfZXi2YHdG7X7Q4e5x2vvPAqu+HPINP/1SrZqrS7QPcsUdO9RS61emcXj1YCvpw1qsYMOf7vPPopcZhMOWQqSXBSXfINs9IUERnoLbW+qzKEcobtgBeOQaxGaFHKjgLPr3nlu6wOVy2fbQPgyEtNGIIOBdtyyHsfdlLp0J7k7FoI3Wz+ZMN7HVrgqF96Cab1wtXcx/hsTTvRJbq9V7vIr5Jgx2qV6AACKrGdaiaZm+H8S/qBbnth867awTniA6mtUI2HIl2ESQ1amvTpEo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
